Dump and load from stdio
zweitag/yaml_db_anonymizer pull request #2
Opened 2017-07-11 08:02 UTC by pmk1c

Dump / load data to / from stdio

2017-07-12 09:37 UTC, djmaze requested changes

2017-07-12 09:37 UTC, djmaze commented on lib/tasks/yaml_db_anonymizer.rake
> +    end
This is quite [dangerous](http://techblog.thescore.com/2016/03/17/defined-methods-in-rake-tasks-you-re-gonna-have-a-bad-time/). Maybe just put this in a module, as described in the post?

2017-07-12 13:26 UTC, pmk1c commented on lib/tasks/yaml_db_anonymizer.rake
> +    end
Good catch. Since it isn't very complex, and the functionality is only needed for the rake tasks, I'd just put it into the tasks.

2017-09-04 13:42 UTC, padde commented
@djmaze good to go now?

2017-09-04 15:47 UTC, djmaze approved these changes

2017-09-04 15:47 UTC, djmaze commented
@padde Yes! Sorry for missing out on this.

2017-09-05 07:19 UTC, padde commented
@djmaze can you please merge? I don't have write access to this repo and we need these changes for THP.

2017-09-05 07:59 UTC, merged